[package]
name = "kwait"
version = "0.1.0"
authors = ["bin liu <liubin0329@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7"
scopeguard = "1.1.0"
rand = "0.7"
